"""empty message

Revision ID: 356db93f4056
Revises: f9beab256065
Create Date: 2019-10-12 18:37:08.282036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356db93f4056'
down_revision = 'f9beab256065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recircle_user', sa.Column('rest_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recircle_user', 'rest_day')
    # ### end Alembic commands ###
