"""empty message

Revision ID: 58cb9561d1a6
Revises: c32e4cde6b37
Create Date: 2019-10-12 15:00:00.306783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cb9561d1a6'
down_revision = 'c32e4cde6b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_info', sa.Column('adminName', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_store_info_adminName'), 'store_info', ['adminName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_info_adminName'), table_name='store_info')
    op.drop_column('store_info', 'adminName')
    # ### end Alembic commands ###
