"""empty message

Revision ID: c32e4cde6b37
Revises: 
Create Date: 2019-10-09 22:44:50.364415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32e4cde6b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recircle_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('telnum', sa.String(length=11), nullable=False),
    sa.Column('ip_addr', sa.PickleType(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=False),
    sa.Column('right_chinese', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recircle_user_account'), 'recircle_user', ['account'], unique=True)
    op.create_index(op.f('ix_recircle_user_company'), 'recircle_user', ['company'], unique=False)
    op.create_index(op.f('ix_recircle_user_contact'), 'recircle_user', ['contact'], unique=False)
    op.create_index(op.f('ix_recircle_user_ip_addr'), 'recircle_user', ['ip_addr'], unique=False)
    op.create_index(op.f('ix_recircle_user_telnum'), 'recircle_user', ['telnum'], unique=False)
    op.create_table('store_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('store_address', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Float(precision=10), nullable=True),
    sa.Column('comment_num', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('web_link', sa.String(length=128), nullable=True),
    sa.Column('web', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_info_city'), 'store_info', ['city'], unique=False)
    op.create_index(op.f('ix_store_info_comment_num'), 'store_info', ['comment_num'], unique=False)
    op.create_index(op.f('ix_store_info_phone_number'), 'store_info', ['phone_number'], unique=False)
    op.create_index(op.f('ix_store_info_store_address'), 'store_info', ['store_address'], unique=False)
    op.create_index(op.f('ix_store_info_store_name'), 'store_info', ['store_name'], unique=True)
    op.create_index(op.f('ix_store_info_time'), 'store_info', ['time'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('telnum', sa.String(length=11), nullable=False),
    sa.Column('ip_addr', sa.PickleType(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=False),
    sa.Column('right_chinese', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.Column('out_count', sa.Integer(), nullable=True),
    sa.Column('data_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account'), 'user', ['account'], unique=True)
    op.create_index(op.f('ix_user_company'), 'user', ['company'], unique=False)
    op.create_index(op.f('ix_user_contact'), 'user', ['contact'], unique=False)
    op.create_index(op.f('ix_user_ip_addr'), 'user', ['ip_addr'], unique=False)
    op.create_index(op.f('ix_user_telnum'), 'user', ['telnum'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telnum'), table_name='user')
    op.drop_index(op.f('ix_user_ip_addr'), table_name='user')
    op.drop_index(op.f('ix_user_contact'), table_name='user')
    op.drop_index(op.f('ix_user_company'), table_name='user')
    op.drop_index(op.f('ix_user_account'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_store_info_time'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_store_name'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_store_address'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_phone_number'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_comment_num'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_city'), table_name='store_info')
    op.drop_table('store_info')
    op.drop_index(op.f('ix_recircle_user_telnum'), table_name='recircle_user')
    op.drop_index(op.f('ix_recircle_user_ip_addr'), table_name='recircle_user')
    op.drop_index(op.f('ix_recircle_user_contact'), table_name='recircle_user')
    op.drop_index(op.f('ix_recircle_user_company'), table_name='recircle_user')
    op.drop_index(op.f('ix_recircle_user_account'), table_name='recircle_user')
    op.drop_table('recircle_user')
    # ### end Alembic commands ###
