"""empty message

Revision ID: f9beab256065
Revises: 58cb9561d1a6
Create Date: 2019-10-12 18:35:34.567450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9beab256065'
down_revision = '58cb9561d1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recircle_user', sa.Column('delete_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recircle_user', 'delete_time')
    # ### end Alembic commands ###
